### ISSUE TITLE
Add 'disk signature' argument to 'make'?

### ISSUE THREAD

**Issue by djs55** [mirage/ocaml-mbr#1]
We want to encourage users of this library to specify a disk signature, which could be used by an OS (like Mirage) to identify the disk.

**Comment by Burnleydev1** [comment]
Hello @reynir, I would like to work on this issue, please can you assign it to me. Thanks.

**Comment by reynir** [comment]
Hello @Burnleydev1. I suggest looking at the wikipedia page on [master boot record](https://en.wikipedia.org/wiki/Master_boot_record). It is the "modern standard MBR" we use. It is the `make` function you will need to modify: https://github.com/mirage/ocaml-mbr/blob/9c8707b19a72c878390ca664a79549ac2eb8e5be/lib/mbr.ml#L165

When working on the code you can use `dune build` to build and compile the project, and `dune runtest` to run the tests. It would be good to add tests, but feel free to create a draft pull request so we can give feedback.

**Comment by Burnleydev1** [comment]
Hello @reynir, please from this [code](https://github.com/mirage/ocaml-mbr/blob/9c8707b19a72c878390ca664a79549ac2eb8e5be/lib/mbr.ml#L209) you pointed to, there is a disk signature argument at line 209 already, so I wish to ask if maybe the fix existed already.

**Comment by reynir** [comment]
Yes, it's already there. But if you look a few lines up:
https://github.com/mirage/ocaml-mbr/blob/9c8707b19a72c878390ca664a79549ac2eb8e5be/lib/mbr.ml#L200
the `disk_signature` is a constant zero (`0l` as it is an int32). What we would like is to allow you to pass in a different value.

**Comment by Burnleydev1** [comment]
Does this mean I can pass any unique value as long as it is int32?
For instance `let disk_signature = 0xA1B2C3D4l`

**Comment by Burnleydev1** [comment]
Hello @reynir, I'm sorry for asking too many questions, but will we have to check for the correctness of the int32?

**Comment by reynir** [comment]
What would you check for? I think every int32 value is valid

**Comment by Burnleydev1** [comment]
This means will replace the line `let disk_signature = 0l in ` to `let disk_signature_str = read_line () in`
and direct the user to input an int32 value.

**Comment by Burnleydev1** [comment]
Hello @reynir, when I ran `dune build` I got the error
 ```
File "lib/dune", line 6, characters 12-19:
6 |  (libraries cstruct)
                ^^^^^^^
Error: Library "cstruct" not found.
-> required by library "mbr-format" in _build/default/lib
-> required by _build/default/META.mbr-format
-> required by alias all
-> required by alias default
File "test/dune", line 3, characters 16-24:
3 |  (libraries mbr alcotest fmt))
                    ^^^^^^^^
Error: Library "alcotest" not found.
-> required by _build/default/test/test_mbr.exe
-> required by alias test/all
-> required by alias default
File "lib/dune", line 5, characters 7-18:     
5 |   (pps ppx_cstruct))
           ^^^^^^^^^^^
Error: Library "ppx_cstruct" not found.
-> required by _build/default/lib/mbr.pp.ml
-> required by alias lib/all
-> required by alias default
```

**Comment by reynir** [comment]
To install the required dependencies you can run `opam install --deps-only .`

**Comment by PizieDust** [comment]
> Thank you @reynir, I did that and it worked, I tried adding the disk_signature to the make function like this
> 
> ```
> let make partitions disk_signature =
>   (if List.length partitions <= 4 then Ok () else Error "Too many partitions")....
> ```
> 
> but I noticed that the function could only take one parameter please I am currently researching the correct way of doing this. please bare with me as I am still very new to ocaml and how it works.

Hello @Burnleydev1 
I think you also have to update the interface file `mbr.mli` so it recognizes the added parameter. 

```ocaml
val make : Partition.t list -> int32 -> (t, string) result
```
where `int32` represents the type for `disk_signature`. 
I'm a beginner too so maybe there could be some errors but I think when we update the function we have to update the interface file. Let me know if it works.

**Comment by Burnleydev1** [comment]
Hello @PizieDust, thanks for helping, i added this to the `mb.mli` and got a new error 
```File "test/test_mbr.ml", line 58, characters 4-8:
58 |   | Ok _ -> ()
         ^^^^
Error: This pattern should not be a constructor, the expected type is
       int32 -> (Mbr.t, string) result
```
this error was showing in the test_mbr.ml file.

**Comment by Burnleydev1** [comment]
It worked and it seems that the test file will have to updated to work with this new changes

**Comment by AryanGodara** [comment]
@reynir ,Can I give this a try, since I did something similar for #20 (reconsider ty argument)
It'll be quicker to implement this one too
