### ISSUE TITLE
Outreachy Persistent Storage issues

### ISSUE THREAD

**Issue by reynir** [mirage/ocaml-mbr#15]
Below you may find open issues that are good first issues as a Outreachy applicant. See also https://github.com/mirage/mirage/issues/1402 if you haven't already. This issue may be updated with more issues.

# ocaml-mbr
- https://github.com/mirage/ocaml-mbr/issues/1
- https://github.com/mirage/ocaml-mbr/issues/12
- https://github.com/mirage/ocaml-mbr/issues/14
- https://github.com/mirage/ocaml-mbr/issues/16

# ocaml-tar
- https://github.com/mirage/ocaml-tar/issues/107

# mirage-block-partition
- https://github.com/reynir/mirage-block-partition/issues/6
- https://github.com/reynir/mirage-block-partition/issues/8

**Comment by dianaoigo** [comment]
I am going through the issues and all of them have been assigned to someone. Can you please assign me one too? @reynir

**Comment by reynir** [comment]
@dianaoigo https://github.com/mirage/ocaml-tar/issues/107 is still unassigned. You can as well work on https://github.com/reynir/mirage-block-partition/issues/6.

**Comment by dianaoigo** [comment]
@reynir perfect. i'll work on mirage/ocaml-tar/issues/107.

**Comment by reynir** [comment]
I added another good first issue https://github.com/reynir/mirage-block-partition/issues/8

**Comment by dianaoigo** [comment]
@reynir i was stuck om the other issue you assigned me and you've been missing in action to help but it's okay. Therefore, i decided to look into issue #15 and so far the code below is what i have so far. any comments

[https://github.com/dianaoigo/mirage-block-partition](url)
  let disconnect b =

    (* XXX disconnect both?! *)
     b.attached <- false;
     Lwt.return_unit
    B.disconnect b.b
end

**Comment by reynir** [comment]
As the Outreachy contribution period is over I'm closing this issue. Thanks a lot to everyone who participated!
