### ISSUE TITLE
Remove dependency on ppx_cstruct

### ISSUE THREAD

**Issue by reynir** [mirage/ocaml-mbr#16]
[Ppx_cstruct](https://github.com/mirage/ocaml-cstruct#ppx) is a preprocessor for OCaml that helps generate code to manipulate C structures from OCaml. These functions are handy, but unfortunately ppx_cstruct has some rather large dependencies, and a few of the generated functions we don't use at all.

Ppx_cstruct is used in two places:

https://github.com/mirage/ocaml-mbr/blob/9c8707b19a72c878390ca664a79549ac2eb8e5be/lib/mbr.ml#L213-L228

https://github.com/mirage/ocaml-mbr/blob/9c8707b19a72c878390ca664a79549ac2eb8e5be/lib/mbr.ml#L103-L112

The code generated by the ppx can be inspected, after running `dune build`, by running `ocamlc -stop-after parsing -dsource _build/default/lib/mbr.pp.ml`.

We do not need to keep the intermediary types `partition` and `mbr`.

It can be useful to define bindings `mbr_*_off` (e.g. `mbr_disk_signature_off`) and use `Cstruct.LE.get_*` and `Cstruct.LE.set_*` as in this PR:  https://github.com/mirage/mirage-profile/pull/40/files

**Comment by 0x0god** [comment]
I'm currently working on this too,

I ran the `dune build` and it works fine after i installed require modules too it shows the below output after I ran 'ocamlc -stop-after parsing -dsource _build/default/lib/mbr.pp.ml' 

The Output: https://paste.opendev.org/show/bw3IRBSy6xlmpW3iaBGE/

So, how do I go about the output? THANKS.

**Comment by reynir** [comment]
> I'm currently working on this too,
> 
> I ran the `dune build` and it works fine after i installed require modules too it shows the below output after I ran 'ocamlc -stop-after parsing -dsource _build/default/lib/mbr.pp.ml'
> 
> The Output: https://paste.opendev.org/show/bw3IRBSy6xlmpW3iaBGE/
> 
> So, how do I go about the output? THANKS.

The output is to inspect what code ppx_cstruct generates. It may be handy as a reference.

One way to go forward is to delete the two occurrences of `[%%cstruct ...]` linked to above, and then let the compiler errors from running `dune build` guide you to what functions you need to implement or where you need to change the code.

**Comment by 0x0god** [comment]
> > I'm currently working on this too,
> > I ran the `dune build` and it works fine after i installed require modules too it shows the below output after I ran 'ocamlc -stop-after parsing -dsource _build/default/lib/mbr.pp.ml'
> > The Output: https://paste.opendev.org/show/bw3IRBSy6xlmpW3iaBGE/
> > So, how do I go about the output? THANKS.
> 
> The output is to inspect what code ppx_cstruct generates. It may be handy as a reference.
> 
> One way to go forward is to delete the two occurrences of `[%%cstruct ...]` linked to above, and then let the compiler errors from running `dune build` guide you to what functions you need to implement or where you need to change the code.

Ooh i get...let me try that

**Comment by 0x0god** [comment]
I deleted the two occurrences of `[%%cstruct ...]` and i was able to fix the first error after running `dune build` .

How do I go about this second error? 

![image](https://user-images.githubusercontent.com/37302024/225773371-9480faa0-e479-4e25-a8a2-65f9dd1ce99d.png)

**Comment by reynir** [comment]
> I deleted the two occurrences of `[%%cstruct ...]` and i was able to fix the first error after running `dune build` .
> 
> How do I go about this second error?
> 
> ![image](https://user-images.githubusercontent.com/37302024/225773371-9480faa0-e479-4e25-a8a2-65f9dd1ce99d.png)

`get_part_ty` is a function generated by ppx_cstruct. You can find the definition in the output you pasted.

**Comment by 0x0god** [comment]
ooh, just saw that it stores a `Cstruct lib function`, which means I need to remove the line right?

**Comment by 0x0god** [comment]
am I on the right path?

**Comment by 0x0god** [comment]
![image](https://user-images.githubusercontent.com/37302024/228790064-845b54aa-c804-4c95-b82d-7071fe4e4c0f.png)

Which of these tasks would recommend to starters?

thanks

**Comment by reynir** [comment]
I would recommend that you choose tasks from what your own interests are. The first two tasks I would recommend as a minimum.

**Comment by 0x0god** [comment]
Okay thanks noted, I just opened a PR....Please help review it thanks.

**Comment by 0x0god** [comment]
Also, I noticed you have not yet added me as an assignee to this issue, Thanks

**Comment by 0x0god** [comment]
I would like to ask if my solution helps, Thanks.

**Comment by reynir** [comment]
Well, I already knew how to do this.
